const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const schema = new Schema({
    username: { type: String, unique: true, required: true },
    userId: {type: String, required: true}, //Custom id generated by front-end server
    hash: { type: String, required: true },
    createdDate: { type: Date, default: Date.now },
    bio: { type: String},
    pic: { type: String},
    friends: []
});

schema.set('toJSON', {
    virtuals: true,
    versionKey: false,
    transform: function (doc, ret) {
        delete ret._id;
        delete ret.hash;
    }
});

module.exports = mongoose.model('User', schema);